# https://jekyllrb.com/docs/

title: Lei4519's Blog
description: >-
  前端，骑行 技术、心得、分享记录

email: lei4519@126.com
github_username: lei4519
baseurl: "/blog"

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules/",
    "vendor/",
    "target/",
    "src/",
    "style/",
  ]

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: "lei4519"
